using Test
using OpSum
using OpSum: instantiate, mpo_terms, irrep_mpo, irrep_mpo_tensors, nrows, total
using TensorKit
using Random: Xoshiro, shuffle
using MatrixAlgebraKit: truncrank, trunctol
using LinearAlgebra: dot, norm

include(joinpath(@__DIR__, "testutils.jl"))   # physmatrix, densedim

# Property tests over *random* term sums
# ======================================
# Everything else in the suite tests hand-written models, which means it tests the term shapes a human
# thought to write. The sweep's state is a `(prefix class, running bond charge)` pair, and the running
# charge only becomes distinguishing when several terms share a prefix of letters but differ in how
# those letters are coupled — a caterpillar inner line — which is precisely what a hand-written model
# rarely varies. Differential testing against the old transient-frontier oracle could not cover it
# either: that oracle had no charge component.
#
# So the terms are generated by **projecting random symmetric `K`-site operators**. `project` returns
# every representable (letters, tree) combination with a random coefficient, so one call sweeps the
# whole term space over those sites — every inner line, every letter, in one shot — and the generator
# inherits `project`'s own faithfulness check as a precondition.

const PROPERTY_SPACES = [
    "Trivial" => ℂ^2,
    "U1Irrep" => Rep[U₁](0 => 1, 1 => 1),
    "SU2Irrep" => SU2Space(1 // 2 => 1),
    "FermionNumber" => Vect[FermionNumber](0 => 1, 1 => 1),
]

# `K` random active sites out of `1:N`, ascending (`project`'s and the sweep's convention).
randsites(rng, N, K) = sort!(shuffle(rng, collect(1:N))[1:K])

"""
A random charge-neutral term sum on `N` sites: one `project`ed random block per entry of `Ks`.
`K = 0` contributes the identity term, which is the one shape `project` cannot produce.
"""
function random_termsum(rng, V, N, Ks)
    I = sectortype(V)
    parts = TermSum{I}[]
    for K in Ks
        if iszero(K)
            push!(parts, scalarop(randn(rng, ComplexF64), V)[1])
            continue
        end
        sites = randsites(rng, N, K)
        Vs = fill(V, K)
        h = randn(rng, ComplexF64, foldl(⊗, Vs) ← foldl(⊗, Vs))
        push!(parts, project(h, sites))
    end
    return onlattice(sum(parts), fill(V, N))
end

@testset "random term sums compress losslessly — $name" for (name, V) in PROPERTY_SPACES
    N = 5
    for seed in (1, 2, 3)
        rng = Xoshiro(seed)
        H = random_termsum(rng, V, N, [0, 1, 1, 2, 2, 2, 3, 3])
        @test !isempty(H)
        # every term is charge-neutral, so the right boundary bond must be trivial
        @test all(k -> total(k) == unit(sectortype(V)), keys(H))
        @test islossless(H)
        Ws, secs = irrep_mpo(H)
        @test length(secs) == N
        @test secs[N] == [unit(sectortype(V))]
        # the compression is a compression: no bond may exceed the term count
        @test all(length(s) <= nrows(H) + 1 for s in secs)
        # The lossless SVD keeps the exact numerical bond rank, which the min-vertex-cover bounds
        # above. (It cannot be checked with `islossless`: an SVD bond basis is a *mixture* of prefix
        # states, so `mpo_terms` enumerates every path and returns thousands of terms whose round-off
        # coefficients do not cancel to exactly zero. The operator-level check is below.)
        for alg in (SVDBondAlgorithm(), SVDBondAlgorithm(; sweep = SequentialSVD))
            _, ssvd = irrep_mpo(H, alg)
            @test all(densedim(ssvd, b) <= densedim(secs, b) for b in 1:N)
        end
    end
end

@testset "K = 4 terms — $name" for (name, V) in PROPERTY_SPACES
    # `K ≥ 4` was previously exercised only by `examples/multibody.jl`. A four-site term is the first
    # one with *two* caterpillar inner lines, so it is the first that can distinguish two couplings of
    # the same four letters.
    N = 5
    rng = Xoshiro(7)
    H = random_termsum(rng, V, N, [4, 4, 2])
    @test !isempty(H)
    @test islossless(H)
    @test maximum(length(k.sites) for k in keys(H)) == 4
    Ws, secs = irrep_mpo(H)
    @test secs[N] == [unit(sectortype(V))]
    # the Jordan emission has to survive the same terms
    Js = jordan_mpo_tensors(H)
    @test length(Js) == N
    @test size(Js[1], 1) == 1 && size(Js[N], 4) == 1
end

@testset "random term sums assemble to the same tensor — $name" for (name, V) in
    PROPERTY_SPACES[[3, 4]]
    # The dense oracle, on the two sectors where a fusion coefficient or a braiding sign could be
    # wrong. Contracting an N-site MPO costs a fresh `ncon` specialization per (length, sectortype),
    # so it runs at one size, on one seed, for two sectors — the symbolic check above is the one that
    # runs broadly.
    N = 4
    H = random_termsum(Xoshiro(11), V, N, [0, 1, 2, 2, 3])
    exact = instantiate(H)
    Ws, secs = irrep_mpo(H)
    @test mpo_tensormap(irrep_mpo_tensors(Ws, secs, fill(V, N))) ≈ exact
    @test mpo_tensormap(map(TensorMap, jordan_mpo_tensors(H))) ≈ exact
    # the SVD bond bases represent the same operator, which is what `islossless` cannot say for them
    for alg in (SVDBondAlgorithm(), SVDBondAlgorithm(; sweep = SequentialSVD))
        Wsv, ssv = irrep_mpo(H, alg)
        @test mpo_tensormap(irrep_mpo_tensors(Wsv, ssv, fill(V, N))) ≈ exact
    end
end

# Truncation quality
# ==================
# The existing SVD tests check that truncation *changes* the operator (`!(Mtrunc ≈ Mexact)`) and that
# the bond shrinks. Neither says the approximation is any good, which is the only reason to truncate.

# A long-range Heisenberg chain: its exact bond dimension grows with `N`, so there is a real spectrum
# of singular values to truncate rather than a handful of exactly-needed channels.
function powerlaw_chain(V, N; α = 2.0)
    S = spin(V)
    return onlattice(
        sum(
            [
                abs(m - n)^(-α) * dot(S[n], S[m]) for n in 1:(N - 1) for m in (n + 1):N
            ]
        ),
        fill(V, N)
    )
end

const TRUNC_V = SU2Space(1 // 2 => 1)
const TRUNC_N = 5
const TRUNC_H = powerlaw_chain(TRUNC_V, TRUNC_N)
const TRUNC_EXACT = instantiate(TRUNC_H)
const TRUNC_NORM = norm(TRUNC_EXACT)

# Relative error of the *assembled* MPO against the exact operator. Not `islossless`: an SVD bond
# basis is a mixture of prefix states, so `mpo_terms` enumerates every path and the round-off
# coefficients of the spurious ones do not cancel to exactly zero. Truncation has to be judged on the
# operator, which is what this measures.
function mpo_relerror(alg)
    Ws, secs = irrep_mpo(TRUNC_H, alg)
    Os = irrep_mpo_tensors(Ws, secs, fill(TRUNC_V, TRUNC_N))
    return norm(mpo_tensormap(Os) - TRUNC_EXACT) / TRUNC_NORM
end

nondecreasing(xs) = all(xs[i + 1] <= xs[i] + 1.0e-12 for i in 1:(length(xs) - 1))

@testset "truncation error decreases with the retained rank" begin
    errs = [mpo_relerror(SVDBondAlgorithm(truncrank(k))) for k in 1:6]
    @test nondecreasing(errs)
    # The bottom of the range keeps nothing usable: `truncrank` truncates globally across sectors with
    # the quantum dimensions counted, so on a spin-½ chain the smallest ranks cannot hold even one
    # spin-1 channel and the MPO collapses to zero — relative error exactly one, not merely large.
    # (Same reason `truncrank` is not in units of reduced bond indices: the lossless bond dimensions
    # here are [2, 4, 4, 2, 1], yet rank 5 is still lossy.)
    @test errs[1] ≈ 1
    # and the top of it is a genuine approximation, an order of magnitude down
    @test errs[end] < 0.1
    # a rank generous enough to keep every channel is lossless again
    @test mpo_relerror(SVDBondAlgorithm(truncrank(1000))) < 1.0e-10
end

@testset "trunctol at the API level" begin
    # `trunctol` was imported by the SVD tests and never exercised. Unlike `truncrank` it is stated in
    # the units of the thing being approximated, which is what makes the error bound below meaningful.
    _, sfull = irrep_mpo(TRUNC_H, SVDBondAlgorithm())

    # a tolerance below round-off keeps everything
    _, stight = irrep_mpo(TRUNC_H, SVDBondAlgorithm(trunctol(; rtol = 1.0e-14)))
    @test [length(s) for s in stight] == [length(s) for s in sfull]
    @test mpo_relerror(SVDBondAlgorithm(trunctol(; rtol = 1.0e-14))) < 1.0e-10

    # a loose tolerance drops channels, and — unlike `truncrank` at the same aggression — the error
    # stays of the tolerance's order rather than the operator's
    alg = SVDBondAlgorithm(trunctol(; rtol = 0.1))
    _, sloose = irrep_mpo(TRUNC_H, alg)
    @test any(length(sloose[b]) < length(sfull[b]) for b in 1:(TRUNC_N - 1))
    @test all(length(sloose[b]) <= length(sfull[b]) for b in 1:TRUNC_N)
    @test mpo_relerror(alg) < 0.1

    # tightening the tolerance may not make the approximation worse, and takes it to zero
    errs = [mpo_relerror(SVDBondAlgorithm(trunctol(; rtol = r))) for r in (0.3, 0.1, 0.03, 0.01)]
    @test nondecreasing(errs)
    @test errs[end] < 1.0e-10

    # and it composes with a rank cap the way `MatrixAlgebraKit` composes strategies
    @test mpo_relerror(SVDBondAlgorithm(truncrank(1000) & trunctol(; rtol = 1.0e-14))) < 1.0e-10
end
