# Reduced MPO for the ITO automaton: reconstruction + symmetric tensors
# =====================================================================
# `irrep_mpo` compresses an ITO `TermSum` into a reduced MPO — site tensors of ITO letters times
# reduced coefficients, plus per-bond charge sectors — by running the per-bond-sector bipartite
# min-vertex-cover sweep `_irrep_graph_bipartite` over the flat `ITOTermTable` (see irrepgraph.jl;
# the transient-frontier `_irrep_bipartite` in irreptermtable.jl is kept as the parity oracle).
# Each retained bond index has a single, well-defined charge (`ITOKey.bond`); block-diagonality is
# `@assert`ed there. Supported scope: K ≤ 2 active sites per term.
#
# This file adds the two consumers of that reduced data:
# * `mpo_terms`         — reconstruct the original `TermSum` by enumerating MPO paths (faithfulness);
# * `irrep_mpo_tensors` — assemble the symmetric MPO `TensorMap`s.

using SparseArrays: SparseMatrixCSC
using TensorKit: Vect, ElementarySpace, fusiontrees, permute, dim, unit, isomorphism, @tensor
using .IrrepTensorOperators: IrrepOperator

"""
    irrep_mpo(H::TermSum, sites) -> (Ws, bondsectors)

Compress the ITO Hamiltonian `H` over `N = length(sites)` lattice sites into a reduced MPO.

Returns `Ws::Vector{SparseMatrixCSC{LocalOp{ComplexF64, IrrepOperator{I}}, Int}}` (one reduced bond
matrix per site; entries are ITO letters times reduced coefficients) and `bondsectors::Vector{
Vector{I}}` where `bondsectors[i]` gives the bond charge of each bond index to the right of site
`i` (so `size(Ws[i], 2) == length(bondsectors[i])`). The left boundary (bond 0) is a single
trivial-charge index.
"""
function irrep_mpo(H::TermSum{I, S, Tc}, sites) where {I, S, Tc}
    return irrep_mpo(H, sites, BipartiteAlgorithm())
end

function irrep_mpo(H::TermSum{I, S, Tc}, sites, ::BipartiteAlgorithm) where {I, S, Tc}
    return _irrep_graph_bipartite(ITOTermTable(H, sites), length(sites))
end

"""
    irrep_mpo(H::TermSum, sites, alg::SVDBondAlgorithm) -> (Ws, bondsectors)

SVD-based reduced MPO: same `(Ws, bondsectors)` contract as the default bipartite construction, but
each bond's compressed basis is chosen by an SVD of the (charge-graded) bond coefficient matrix
rather than a minimum vertex cover. Truncation is set by `alg.trunc` (a `MatrixAlgebraKit`
truncation strategy such as `truncrank`/`trunctol`, applied globally across charge sectors);
`SVDBondAlgorithm()` keeps the lossless default. The compression acts on the symbolic bond
coefficients, so the output still feeds `irrep_mpo_tensors` unchanged.
"""
function irrep_mpo(H::TermSum{I, S, Tc}, sites, alg::SVDBondAlgorithm) where {I, S, Tc}
    return _irrep_svd(ITOTermTable(H, sites), length(sites), alg.trunc)
end

"""
    mpo_terms(Ws, bondsectors) -> TermSum{I, Int, ComplexF64}

Reconstruct the term-sum generated by a reduced MPO (inverse of `irrep_mpo` at the reduced level):
enumerate every path through the bond matrices, multiply the reduced coefficients along it, read
the active ITO letters (skipping pass-through), and rebuild each term's caterpillar tree from the
per-active-site outgoing bond charges (`_tree_from_bonds`; multiplicity-free ⇒ trivial vertices).
For the lossless bipartite compression this recovers the original `TermSum` exactly — the
faithfulness check.
"""
function mpo_terms(
        Ws::Vector{<:SparseMatrixCSC{LocalOp{ComplexF64, IrrepOperator{I}}}},
        bondsectors::Vector{Vector{I}}
    ) where {I}
    N = length(Ws)
    d = Dictionary{TermKey{I, Int}, ComplexF64}()
    N == 0 && return TermSum{I, Int, ComplexF64}(d)

    function walk(i, leftidx, coeff, letters, bonds)
        if i > N
            sites = Int[]
            ops = IrrepOperator{I}[]
            for (k, op) in enumerate(letters)
                ispassthrough(op) || (push!(sites, k); push!(ops, op))
            end
            tree = _tree_from_bonds([o.c for o in ops], bonds, ones(Int, length(ops)))
            setwith!(+, d, TermKey{I, Int}(sites, ops, tree), coeff)
            return
        end
        for (idx, localop) in storedpairs(Ws[i])
            l, r = Tuple(idx)
            l == leftidx || continue
            for (letter, c) in _local_terms(localop)
                letter === nothing && continue
                # record the outgoing bond charge for active (non-pass-through) letters — these are
                # the caterpillar running bonds `[b₁ … b_K]`
                newbonds = ispassthrough(letter) ? bonds : push!(copy(bonds), bondsectors[i][r])
                walk(i + 1, r, coeff * c, push!(copy(letters), letter), newbonds)
            end
        end
        return
    end
    walk(1, 1, ComplexF64(1), IrrepOperator{I}[], I[])
    return TermSum{I, Int, ComplexF64}(d)
end

# Phase 5: assemble symmetric MPO TensorMaps from the reduced bond data
# =====================================================================
# Each site tensor is `W_i : B_{i-1} ⊗ V_i ← V_i ⊗ B_i` (MPSKit convention: left virtual ⊗ physical
# out ← physical in ⊗ right virtual), a symmetric `TensorMap` whose virtual legs `B` are
# `GradedSpace`s built from the per-sector bond multiplicities. Contracting the chain (trivial
# boundary bonds) recovers the operator.

# GradedSpace on a bond with the given per-index charges (multiplicity = count per sector).
function _bond_space(sec::Vector{I}) where {I}
    counts = Dict{I, Int}()
    for c in sec
        counts[c] = get(counts, c, 0) + 1
    end
    return Vect[I](counts)
end

# degeneracy index (within its charge sector) of each bond index
function _deg_indices(sec::Vector{I}) where {I}
    counts = Dict{I, Int}()
    out = Vector{Int}(undef, length(sec))
    for (j, c) in enumerate(sec)
        counts[c] = get(counts, c, 0) + 1
        out[j] = counts[c]
    end
    return out
end

# Contract one letter's accumulated bond coupler into the site tensor. Split out so that `@tensor`
# specialises on the concrete tensor types even though the per-site memo tables below are
# heterogeneously typed.
function _add_bond_entry!(W, O, κ)
    @tensor W[bl o; ii br] += O[o; ii cc] * κ[bl cc; br]
    return W
end

# Write one reduced coefficient into a coupler block. Also a function barrier: this runs once per
# *stored bond entry* — `O(D_L · D_R)` of them, against `O(d²)` contractions above — so it is the loop
# that must not stay dynamically dispatched off the memo tables' `Any` element type.
function _add_coupler_coeff!(κ, f1, f2, dL::Int, dR::Int, coeff)
    κ[f1, f2][dL, 1, dR] += coeff
    return κ
end

"""
    irrep_mpo_tensors(Ws, bondsectors, sites) -> Vector{<:AbstractTensorMap}

Assemble the symmetric MPO from the reduced bond matrices + bond sectors (from `irrep_mpo`). Site
tensor `W_i : B_{i-1} ⊗ V_i ← V_i ⊗ B_i` (MPSKit convention); the boundary bonds `B_0`, `B_N` are
one-dimensional.
Each reduced entry `(l, r, letter, coeff)` places the ITO letter's tensor into the `(l → r)` bond
transition weighted by `coeff`, coupling the operator charge into the bond via the (forward)
fusion `b_L ⊗ c → b_R`.
"""
function irrep_mpo_tensors(
        Ws::Vector{<:SparseMatrixCSC{LocalOp{ComplexF64, IrrepOperator{I}}}},
        bondsectors::Vector{Vector{I}}, sites
    ) where {I}
    N = length(Ws)

    # Every internal bond is shared by two site tensors, so build its graded space and degeneracy
    # indices once rather than twice (as `Bright`/`degR` of site i and `Bleft`/`degL` of site i+1).
    # `bsecs[i]` is the bond to the *left* of site i; `bsecs[1]` is the trivial left boundary.
    bsecs = Vector{Vector{I}}(undef, N + 1)
    bsecs[1] = I[unit(I)]
    for i in 1:N
        bsecs[i + 1] = bondsectors[i]
    end
    bspaces = map(_bond_space, bsecs)
    bdegs = map(_deg_indices, bsecs)

    # `map` infers a concrete `Vector{<:AbstractTensorMap}` element type (all site tensors share
    # the same `B ⊗ V ← V ⊗ B` space *type*), unlike an untyped preallocated buffer.
    return map(1:N) do i
        V = sites[i]
        secL, secR = bsecs[i], bsecs[i + 1]
        Bleft, Bright = bspaces[i], bspaces[i + 1]
        degL, degR = bdegs[i], bdegs[i + 1]

        W = zeros(ComplexF64, Bleft ⊗ V ← V ⊗ Bright)

        # Assemble per *letter*, not per entry. The bond coupler κ_letter : Bleft ⊗ Vc ← Bright
        # collects every reduced coefficient carrying that letter, so the site needs one contraction
        # per distinct letter — `O(d²)` of them — instead of one per stored bond entry, of which there
        # are `O(D_L · D_R)`. (The previous form also rebuilt κ, the letter tensor and both fusion
        # trees per entry, and accumulated via an out-of-place `W = W + Wentry` that reallocated and
        # rewrote the whole site tensor every time.)
        ops = Dictionary{IrrepOperator{I}, Any}()
        couplers = Dictionary{IrrepOperator{I}, Any}()
        f1s = Dictionary{Tuple{I, I, I}, Any}()
        f2s = Dictionary{I, Any}()

        for (idx, localop) in storedpairs(Ws[i])
            l, r = Tuple(idx)
            bL, dL = secL[l], degL[l]
            bR, dR = secR[r], degR[r]
            for (letter, coeff) in _local_terms(localop)
                letter === nothing && continue
                c = letter.c
                # V ← V ⊗ Vect[c]; pass-through (c = unit) carries a trivial charge leg so the
                # bond contraction is uniform (instantiate would drop it, returning bare id(V)).
                get!(ops, letter) do
                    Vc = Vect[I](c => 1)
                    return ispassthrough(letter) ? isomorphism(ComplexF64, V ← V ⊗ Vc) :
                        instantiate(letter, V)
                end
                # κ couples the operator charge into the bond by the (forward) fusion (bL, c) → bR —
                # running bond FIRST, then the operator charge, matching the left-nested caterpillar
                # the oracle uses. (Charge-first would agree only for symmetric vertices, e.g. K=2
                # singlets, and flips the sign at antisymmetric inner vertices like 1⊗1→1 for K ≥ 3.)
                κ = get!(couplers, letter) do
                    return zeros(ComplexF64, Bleft ⊗ Vect[I](c => 1) ← Bright)
                end
                f1 = get!(() -> only(fusiontrees((bL, c), bR, (false, false))), f1s, (bL, c, bR))
                f2 = get!(() -> only(fusiontrees((bR,), bR, (false,))), f2s, bR)
                # `(l, r)` determines `(bL, dL, bR, dR)` and the letter fixes `c`, so distinct stored
                # entries always address distinct slots; the `+=` only matters if `_local_terms`
                # returns one letter twice for a single entry.
                _add_coupler_coeff!(κ, f1, f2, dL, dR, coeff)
            end
        end

        for (letter, κ) in pairs(couplers)
            _add_bond_entry!(W, ops[letter], κ)
        end
        return W
    end
end
