name = "OpSum"
uuid = "ad22a312-ed53-41dd-b1d0-052652c9fe0a"
authors = ["Lukas Devos <ldevos98@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LightSumTypes = "f56206fc-af4c-5561-a72a-43fe2ca5a923"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixAlgebraKit = "6c742aac-3347-4629-af66-fc926824e5e4"
SparseArraysBase = "0d5efcca-f356-4864-8770-e1ed8d78f208"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"

[compat]
AbstractTrees = "0.4.5"
Dictionaries = "0.4.3"
LightSumTypes = "5.2.0"
LinearAlgebra = "1.0"
MatrixAlgebraKit = "0.5"
SparseArraysBase = "0.7"
VectorInterface = "0.5.0"
julia = "1.10"
